language: ruby

dist: trusty
sudo: required

cache:
    apt: true

env:
    global:
        - DOCKER_VERSION=17.06.0~ce-0~ubuntu
    matrix:
        - IMAGE_NAME=flow TAG=0.50.0 FLOW_VERSION=0.50.0 OCAML_VERSION=4.03.0
        - IMAGE_NAME=node TAG=8.1.2 FROM_FLOW_FQIN=karibbu/flow:0.49.1 FROM_NODE_FQIN=node:8.1.2-alpine
        - IMAGE_NAME=php TAG=7.1.7 FROM_FQIN=php:7.1.7-zts-alpine COMPOSER_VERSION=1.4.2 PRESTISSIMO_VERSION=0.3.7 PHPCSFIXER_VERSION=2.3.2 PHPSTAN_VERSION=0.7.0 APCUBC_VERSION=1.0.3 RAPHF_VERSION=2.0.0 DS_VERSION=1.1.10 AMQP_VERSION=1.9.1
        - IMAGE_NAME=netutils TAG=1.0.0 FROM_FQIN=alpine:3.6
        - IMAGE_NAME=rabbitmq TAG=3.6.10-1 FROM_FQIN=rabbitmq:3.6.10-alpine

before_install:
    - |
        if [ "$(docker version -f '{{.Server.Version}}')|sed -e 's/-ce.*$//'" != "$(echo $DOCKER_VERSION|sed -e 's/~ce.*$//')" ] ; then
            sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce=${DOCKER_VERSION}
        fi

install:
    - make -C $IMAGE_NAME pull
    - if [ "$(bin/should-run-test.sh)" ]; then
        travis_terminate 0;
      fi

script:
    - make -C $IMAGE_NAME build test

after_success:
    - make -C $IMAGE_NAME tag images

deploy:
    provider: script
    script: make -C $IMAGE_NAME push
    skip_cleanup: true
    on:
        branch: master

notifications:
    slack: verylastroom:yqs3UqNXq6H3L9p8npeVFWgh
    email:
        recipients:
            - ci@karibbu.com
        on_success: change
        on_failure: change

